---
 - hosts: webservers
   name: This playbook will run on webservers
   vars:
     tool: wget

   tasks:
    - name: To uninstall a package called {{ tool }}
      yum:
        name: "{{ tool }}"
        state: absent
